backend: tensorflow
class_name: Model
config:
  input_layers:
  - [input_1, 0, 0]
  layers:
  - class_name: InputLayer
    config:
      batch_input_shape: !!python/tuple [null, 647, 128]
      dtype: float32
      name: input_1
      sparse: false
    inbound_nodes: []
    name: input_1
  - class_name: Conv1D
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dilation_rate: !!python/tuple [1]
      filters: 256
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config: {distribution: normal, mode: fan_avg, scale: 1.0, seed: null}
      kernel_regularizer: null
      kernel_size: !!python/tuple [4]
      name: conv1d_1
      padding: same
      strides: !!python/tuple [2]
      trainable: true
      use_bias: true
    inbound_nodes:
    - - - input_1
        - 0
        - 0
        - {}
    name: conv1d_1
  - class_name: Activation
    config: {activation: relu, name: activation_1, trainable: true}
    inbound_nodes:
    - - - conv1d_1
        - 0
        - 0
        - {}
    name: activation_1
  - class_name: MaxPooling1D
    config:
      name: max_pooling1d_1
      padding: valid
      pool_size: !!python/tuple [2]
      strides: !!python/tuple [2]
      trainable: true
    inbound_nodes:
    - - - activation_1
        - 0
        - 0
        - {}
    name: max_pooling1d_1
  - class_name: Conv1D
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dilation_rate: !!python/tuple [1]
      filters: 256
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config: {distribution: normal, mode: fan_avg, scale: 1.0, seed: null}
      kernel_regularizer: null
      kernel_size: !!python/tuple [4]
      name: conv1d_2
      padding: same
      strides: !!python/tuple [2]
      trainable: true
      use_bias: true
    inbound_nodes:
    - - - max_pooling1d_1
        - 0
        - 0
        - {}
    name: conv1d_2
  - class_name: Activation
    config: {activation: relu, name: activation_2, trainable: true}
    inbound_nodes:
    - - - conv1d_2
        - 0
        - 0
        - {}
    name: activation_2
  - class_name: MaxPooling1D
    config:
      name: max_pooling1d_2
      padding: valid
      pool_size: !!python/tuple [2]
      strides: !!python/tuple [2]
      trainable: true
    inbound_nodes:
    - - - activation_2
        - 0
        - 0
        - {}
    name: max_pooling1d_2
  - class_name: Conv1D
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dilation_rate: !!python/tuple [1]
      filters: 256
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config: {distribution: normal, mode: fan_avg, scale: 1.0, seed: null}
      kernel_regularizer: null
      kernel_size: !!python/tuple [4]
      name: conv1d_3
      padding: same
      strides: !!python/tuple [2]
      trainable: true
      use_bias: true
    inbound_nodes:
    - - - max_pooling1d_2
        - 0
        - 0
        - {}
    name: conv1d_3
  - class_name: Activation
    config: {activation: relu, name: activation_3, trainable: true}
    inbound_nodes:
    - - - conv1d_3
        - 0
        - 0
        - {}
    name: activation_3
  - class_name: MaxPooling1D
    config:
      name: max_pooling1d_3
      padding: valid
      pool_size: !!python/tuple [2]
      strides: !!python/tuple [2]
      trainable: true
    inbound_nodes:
    - - - activation_3
        - 0
        - 0
        - {}
    name: max_pooling1d_3
  - class_name: AveragePooling1D
    config:
      name: average_pooling1d_1
      padding: valid
      pool_size: !!python/tuple [4]
      strides: !!python/tuple [4]
      trainable: true
    inbound_nodes:
    - - - max_pooling1d_3
        - 0
        - 0
        - {}
    name: average_pooling1d_1
  - class_name: MaxPooling1D
    config:
      name: max_pooling1d_4
      padding: valid
      pool_size: !!python/tuple [4]
      strides: !!python/tuple [4]
      trainable: true
    inbound_nodes:
    - - - max_pooling1d_3
        - 0
        - 0
        - {}
    name: max_pooling1d_4
  - class_name: Concatenate
    config: {axis: -1, name: concatenate_1, trainable: true}
    inbound_nodes:
    - - - average_pooling1d_1
        - 0
        - 0
        - &id001 {}
      - - max_pooling1d_4
        - 0
        - 0
        - *id001
    name: concatenate_1
  - class_name: Flatten
    config: {data_format: channels_last, name: flatten_1, trainable: true}
    inbound_nodes:
    - - - concatenate_1
        - 0
        - 0
        - {}
    name: flatten_1
  - class_name: Dense
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
      kernel_regularizer: null
      name: dense_1
      trainable: true
      units: 2048
      use_bias: true
    inbound_nodes:
    - - - flatten_1
        - 0
        - 0
        - {}
    name: dense_1
  - class_name: Dropout
    config: {name: dropout_1, noise_shape: null, rate: 0.5, seed: null, trainable: true}
    inbound_nodes:
    - - - dense_1
        - 0
        - 0
        - {}
    name: dropout_1
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
      kernel_regularizer: null
      name: dense_2
      trainable: true
      units: 10
      use_bias: true
    inbound_nodes:
    - - - dropout_1
        - 0
        - 0
        - {}
    name: dense_2
  - class_name: Dropout
    config: {name: dropout_2, noise_shape: null, rate: 0.5, seed: null, trainable: true}
    inbound_nodes:
    - - - dense_2
        - 0
        - 0
        - {}
    name: dropout_2
  - class_name: Activation
    config: {activation: softmax, name: activation_4, trainable: true}
    inbound_nodes:
    - - - dropout_2
        - 0
        - 0
        - {}
    name: activation_4
  name: model_1
  output_layers:
  - [activation_4, 0, 0]
keras_version: 2.1.6
